<?php

namespace ContainerE3QtlzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P9FnnWKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P9FnnWK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P9FnnWK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'building' => ['privates', '.errored..service_locator.P9FnnWK.App\\Entity\\Building', NULL, 'Cannot autowire service ".service_locator.P9FnnWK": it references class "App\\Entity\\Building" but no such service exists.'],
        ], [
            'building' => 'App\\Entity\\Building',
        ]);
    }
}
