<?php

namespace ContainerE3QtlzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuildingTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BuildingType' shared autowired service.
     *
     * @return \App\Form\BuildingType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\BuildingType.php';

        return $container->privates['App\\Form\\BuildingType'] = new \App\Form\BuildingType();
    }
}
