<?php

namespace ContainerE3QtlzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuildingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.P9FnnWK.App\Entity\Building' shared service.
     *
     * @return \App\Entity\Building
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.P9FnnWK": it references class "App\\Entity\\Building" but no such service exists.');
    }
}
