security:
    encoders:
    # used if previously was used bcrypt for ex.
    #    legacy_bcrypt:
    #        algorithm: bcrypt
        App\Entity\User:
            algorithm: auto
            #cost: 30 higher cost makes pass harder to crack - takes more cpu
     #       migrate_from:
     #           - legacy_bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: logout
                # where to redirect after logout
                target: index

            # default access denied template
            access_denied_handler: App\Security\AccessDeniedHandler
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/buildings, roles: ROLE_ADMIN}
         - { path: ^/offices, roles: ROLE_ADMIN}
         - { path: ^/employees, roles: ROLE_ADMIN}
         - { path: ^/user, roles: ROLE_USER}
        # - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
