<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVWp4ngM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVWp4ngM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVWp4ngM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVWp4ngM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVWp4ngM\App_KernelDevDebugContainer([
    'container.build_hash' => 'VWp4ngM',
    'container.build_id' => 'aa40f24c',
    'container.build_time' => 1595407705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVWp4ngM');
