<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ6J9yvU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ6J9yvU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ6J9yvU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ6J9yvU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ6J9yvU\App_KernelDevDebugContainer([
    'container.build_hash' => 'J6J9yvU',
    'container.build_id' => '87cbf102',
    'container.build_time' => 1599082108,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ6J9yvU');
