<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE3QtlzL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE3QtlzL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE3QtlzL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE3QtlzL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE3QtlzL\App_KernelDevDebugContainer([
    'container.build_hash' => 'E3QtlzL',
    'container.build_id' => '17bb4f98',
    'container.build_time' => 1594816289,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE3QtlzL');
