<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'buildings' => [[], ['_controller' => 'App\\Controller\\BuildingController::home'], [], [['text', '/buildings']], [], []],
    'add' => [[], ['_controller' => 'App\\Controller\\BuildingController::add'], [], [['text', '/building/add']], [], []],
    'edit' => [['id'], ['_controller' => 'App\\Controller\\BuildingController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/building/edit']], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\BuildingController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/building/delete']], [], []],
    'employees' => [[], ['_controller' => 'App\\Controller\\EmployeeController::index'], [], [['text', '/employees']], [], []],
    'add_employee' => [[], ['_controller' => 'App\\Controller\\EmployeeController::addEmployee'], [], [['text', '/employee/add']], [], []],
    'edit_employee' => [['id'], ['_controller' => 'App\\Controller\\EmployeeController::editEmployee'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/employee/edit']], [], []],
    'delete_employee' => [['id'], ['_controller' => 'App\\Controller\\EmployeeController::deleteEmployee'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/employee/delete']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'offices' => [[], ['_controller' => 'App\\Controller\\OfficeController::home'], [], [['text', '/offices']], [], []],
    'add_office' => [[], ['_controller' => 'App\\Controller\\OfficeController::addOffice'], [], [['text', '/office/add']], [], []],
    'edit_office' => [['id'], ['_controller' => 'App\\Controller\\OfficeController::editOffice'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/office/edit']], [], []],
    'delete_office' => [['id'], ['_controller' => 'App\\Controller\\OfficeController::deleteOffice'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/office/delete']], [], []],
];
